### ISSUE TITLE
Is it possible to add support for custom Route53 domain for LB

### ISSUE THREAD

**Issue by mn3m0nic** [lean-delivery/tf-module-aws-alb#5]
Hi Team.

It will be nice to have support for custom Route53 domain name for ALB in addition to current dynamically generated. For example it will be very handy if you have SSL certificate for CN=*.example.com and dynamically generated record "{PROJECT}-{ENV}-{id}.{region} can't be covered currently by simple SSL wildcard.

Thanks

**Comment by ignatovich-artem** [comment]
Fixed in https://github.com/lean-delivery/tf-module-aws-alb/pull/16
